"""Daily planner models: a per-day check-in and user-scheduled time blocks.

The planner is the daily surface of the roadmap engine: roadmaps schedule
tasks onto dates, the planner turns those dates into a real daily agenda and
captures a lightweight daily check-in (focus / mood / energy) alongside the
existing weekly reflection.
"""

from datetime import date, datetime, time

from sqlalchemy import JSON, Boolean, Date, DateTime, ForeignKey, Index, Integer, String, Text, Time, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base
from app.models.enums import DailyCheckinStatus
from app.models.user import sa_enum


class DailyCheckin(Base):
    """One short reflection per calendar day (morning focus + evening wrap-up)."""

    __tablename__ = "daily_checkins"
    __table_args__ = (UniqueConstraint("user_id", "date", name="uq_daily_checkin_user_date"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id", ondelete="CASCADE"), index=True)
    date: Mapped[date] = mapped_column(Date, index=True)

    focus: Mapped[str] = mapped_column(Text, default="")      # what I want to get done today
    done: Mapped[str] = mapped_column(Text, default="")       # evening wrap-up
    mood: Mapped[str] = mapped_column(String(20), default="")
    energy: Mapped[int | None] = mapped_column(Integer, nullable=True)
    note: Mapped[str] = mapped_column(Text, default="")

    ai_summary: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    status: Mapped[DailyCheckinStatus] = mapped_column(
        sa_enum(DailyCheckinStatus), default=DailyCheckinStatus.DRAFT
    )

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class ScheduleBlock(Base):
    """A time-bounded (or open) item on a planner day.

    ``kind``: study | task | priority | class | exam | coach | break
    ``source``: manual | auto   (auto blocks are regenerated by auto-plan)
    ``linked_type``/``linked_id``: optional reference to the source item
    (m3_task, task, priority, roadmap_item) so completion propagates back.
    """

    __tablename__ = "schedule_blocks"
    __table_args__ = (Index("ix_schedule_blocks_user_date", "user_id", "date"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id", ondelete="CASCADE"))
    date: Mapped[date] = mapped_column(Date)

    start_time: Mapped[time | None] = mapped_column(Time, nullable=True)
    end_time: Mapped[time | None] = mapped_column(Time, nullable=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    kind: Mapped[str] = mapped_column(String(30), default="study")
    minutes: Mapped[int] = mapped_column(Integer, default=60)
    source: Mapped[str] = mapped_column(String(30), default="manual")
    linked_type: Mapped[str | None] = mapped_column(String(30), nullable=True)
    linked_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    completed: Mapped[bool] = mapped_column(Boolean, default=False)
    order_index: Mapped[int] = mapped_column(Integer, default=0)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )