"""Master career catalog for NOVI.

Mirrors the canonical master list of careers with country ranking profiles.
Each career is stored with its title, category and ranking profile. The seed
builder enriches every entry with generated detail (skills, subjects, degrees,
salary, outlook) so the whole catalog is browsable and matchable.
"""

NOTE = (
    "No finite list can include literally every possible career because new roles "
    "appear constantly. This is a very broad master list covering all major career "
    "families and common high-paying variations. Country ranking means best to worst "
    "among USA, UK, Australia, India for pay + demand + ecosystem + long-term "
    "opportunity. It does not account for personal visa eligibility or citizenship."
)

RANKING_PROFILES: dict[str, list[str]] = {
    "TECH": ["USA", "UK", "Australia", "India"],
    "AI_DATA": ["USA", "UK", "Australia", "India"],
    "CYBER": ["USA", "UK", "Australia", "India"],
    "FINANCE": ["USA", "UK", "Australia", "India"],
    "LAW": ["USA", "UK", "Australia", "India"],
    "HEALTH": ["USA", "Australia", "UK", "India"],
    "NURSING": ["USA", "Australia", "UK", "India"],
    "DENTAL": ["USA", "Australia", "UK", "India"],
    "PHARMA": ["USA", "UK", "Australia", "India"],
    "ENGINEERING": ["USA", "Australia", "UK", "India"],
    "MINING_ENERGY": ["Australia", "USA", "UK", "India"],
    "TRADES": ["Australia", "USA", "UK", "India"],
    "AVIATION": ["USA", "Australia", "UK", "India"],
    "MARITIME": ["UK", "Australia", "USA", "India"],
    "MEDIA": ["USA", "UK", "India", "Australia"],
    "SPORTS_GLOBAL": ["USA", "UK", "Australia", "India"],
    "CRICKET": ["India", "Australia", "UK", "USA"],
    "FOOTBALL": ["UK", "USA", "Australia", "India"],
    "GOVT": ["USA", "UK", "Australia", "India"],
    "EDU": ["USA", "UK", "Australia", "India"],
    "SCIENCE": ["USA", "UK", "Australia", "India"],
    "HOSPITALITY": ["Australia", "USA", "UK", "India"],
    "AGRICULTURE": ["USA", "Australia", "UK", "India"],
    "LOGISTICS": ["USA", "UK", "Australia", "India"],
    "ENTREPRENEUR": ["USA", "India", "UK", "Australia"],
    "BUSINESS": ["USA", "UK", "Australia", "India"],
    "REAL_ESTATE": ["USA", "Australia", "UK", "India"],
    "PUBLIC_SAFETY": ["USA", "UK", "Australia", "India"],
    "CREATIVE": ["USA", "UK", "Australia", "India"],
    "DEFAULT": ["USA", "UK", "Australia", "India"],
}

# (title, category, ranking_profile)
CAREERS: list[tuple[str, str, str]] = [
    ("Frontend Developer", "Technology", "TECH"),
    ("Backend Developer", "Technology", "TECH"),
    ("Full Stack Developer", "Technology", "TECH"),
    ("Mobile App Developer", "Technology", "TECH"),
    ("iOS Developer", "Technology", "TECH"),
    ("Android Developer", "Technology", "TECH"),
    ("Game Developer", "Technology", "TECH"),
    ("Game Designer", "Technology", "TECH"),
    ("DevOps Engineer", "Technology", "TECH"),
    ("Site Reliability Engineer", "Technology", "TECH"),
    ("Cloud Architect", "Technology", "TECH"),
    ("Solutions Architect", "Technology", "TECH"),
    ("Enterprise Architect", "Technology", "TECH"),
    ("Cybersecurity Analyst", "Technology", "CYBER"),
    ("Penetration Tester", "Technology", "CYBER"),
    ("Security Architect", "Technology", "CYBER"),
    ("Network Engineer", "Technology", "TECH"),
    ("Systems Administrator", "Technology", "TECH"),
    ("Database Administrator", "Technology", "TECH"),
    ("Data Analyst", "Technology", "AI_DATA"),
    ("Data Scientist", "Technology", "AI_DATA"),
    ("Data Engineer", "Technology", "AI_DATA"),
    ("Machine Learning Engineer", "Technology", "AI_DATA"),
    ("AI Research Scientist", "Technology", "AI_DATA"),
    ("NLP Engineer", "Technology", "AI_DATA"),
    ("Computer Vision Engineer", "Technology", "AI_DATA"),
    ("Robotics Engineer", "Technology", "TECH"),
    ("Blockchain Developer", "Technology", "TECH"),
    ("Smart Contract Auditor", "Technology", "TECH"),
    ("Quantum Computing Researcher", "Technology", "AI_DATA"),
    ("AR/VR Developer", "Technology", "TECH"),
    ("Embedded Systems Engineer", "Technology", "TECH"),
    ("Firmware Engineer", "Technology", "TECH"),
    ("QA/Test Automation Engineer", "Technology", "TECH"),
    ("IT Project Manager", "Technology", "TECH"),
    ("Scrum Master", "Technology", "TECH"),
    ("Product Manager", "Technology", "TECH"),
    ("Technical Product Manager", "Technology", "TECH"),
    ("UX/UI Designer", "Technology", "CREATIVE"),
    ("Product Designer", "Technology", "CREATIVE"),
    ("Graphic Designer", "Creative", "CREATIVE"),
    ("Motion Designer", "Creative", "CREATIVE"),
    ("3D Artist", "Creative", "CREATIVE"),
    ("Animator", "Creative", "CREATIVE"),
    ("VFX Artist", "Creative", "CREATIVE"),
    ("Technical Writer", "Technology", "TECH"),
    ("SEO Specialist", "Marketing", "BUSINESS"),
    ("Digital Marketing Manager", "Marketing", "BUSINESS"),
    ("Growth Hacker", "Marketing", "BUSINESS"),
    ("Social Media Manager", "Marketing", "BUSINESS"),
    ("Content Creator/Influencer", "Media", "MEDIA"),
    ("E-commerce Manager", "Business", "BUSINESS"),
    ("Affiliate Marketer", "Marketing", "BUSINESS"),
    ("Bug Bounty Hunter", "Technology", "CYBER"),
    ("Ethical Hacker", "Technology", "CYBER"),
    ("Investment Banker", "Finance", "FINANCE"),
    ("Private Equity Associate", "Finance", "FINANCE"),
    ("Venture Capitalist", "Finance", "FINANCE"),
    ("Hedge Fund Manager", "Finance", "FINANCE"),
    ("Portfolio Manager", "Finance", "FINANCE"),
    ("Financial Analyst", "Finance", "FINANCE"),
    ("Equity Research Analyst", "Finance", "FINANCE"),
    ("Risk Manager", "Finance", "FINANCE"),
    ("Compliance Officer", "Finance", "FINANCE"),
    ("Actuary", "Finance", "FINANCE"),
    ("Accountant/CPA", "Finance", "FINANCE"),
    ("Auditor", "Finance", "FINANCE"),
    ("Tax Consultant", "Finance", "FINANCE"),
    ("Management Consultant", "Business", "BUSINESS"),
    ("Strategy Consultant", "Business", "BUSINESS"),
    ("Operations Manager", "Business", "BUSINESS"),
    ("Supply Chain Manager", "Logistics", "LOGISTICS"),
    ("Logistics Manager", "Logistics", "LOGISTICS"),
    ("Procurement Manager", "Logistics", "LOGISTICS"),
    ("HR Manager", "Business", "BUSINESS"),
    ("Recruiter", "Business", "BUSINESS"),
    ("Sales Director", "Business", "BUSINESS"),
    ("Business Development Manager", "Business", "BUSINESS"),
    ("Marketing Director", "Marketing", "BUSINESS"),
    ("Brand Manager", "Marketing", "BUSINESS"),
    ("Market Research Analyst", "Marketing", "BUSINESS"),
    ("Real Estate Agent", "Real Estate", "REAL_ESTATE"),
    ("Real Estate Developer", "Real Estate", "REAL_ESTATE"),
    ("Property Manager", "Real Estate", "REAL_ESTATE"),
    ("Insurance Broker", "Finance", "FINANCE"),
    ("Financial Advisor", "Finance", "FINANCE"),
    ("Wealth Manager", "Finance", "FINANCE"),
    ("Fintech Product Manager", "Finance", "FINANCE"),
    ("Quant Analyst", "Finance", "FINANCE"),
    ("Algorithmic Trader", "Finance", "FINANCE"),
    ("Credit Analyst", "Finance", "FINANCE"),
    ("Loan Officer", "Finance", "FINANCE"),
    ("Bank Manager", "Finance", "FINANCE"),
    ("CFO", "Finance", "FINANCE"),
    ("CEO", "Business", "BUSINESS"),
    ("Entrepreneur/Startup Founder", "Business", "ENTREPRENEUR"),
    ("Franchise Owner", "Business", "ENTREPRENEUR"),
    ("Small Business Owner", "Business", "ENTREPRENEUR"),
    ("Stock Trader", "Finance", "FINANCE"),
    ("Crypto Investor", "Finance", "FINANCE"),
    ("Angel Investor", "Finance", "FINANCE"),
    ("Airbnb Host", "Business", "ENTREPRENEUR"),
    ("Amazon FBA Seller", "Business", "ENTREPRENEUR"),
    ("Course Creator", "Business", "ENTREPRENEUR"),
    ("Corporate Lawyer", "Law", "LAW"),
    ("IP Lawyer", "Law", "LAW"),
    ("Patent Attorney", "Law", "LAW"),
    ("Tax Lawyer", "Law", "LAW"),
    ("Criminal Lawyer", "Law", "LAW"),
    ("Family Lawyer", "Law", "LAW"),
    ("Immigration Lawyer", "Law", "LAW"),
    ("Real Estate Lawyer", "Law", "LAW"),
    ("Litigation Lawyer", "Law", "LAW"),
    ("Judge", "Law", "LAW"),
    ("Arbitrator/Mediator", "Law", "LAW"),
    ("Legal Consultant", "Law", "LAW"),
    ("Compliance Lawyer", "Law", "LAW"),
    ("Paralegal", "Law", "LAW"),
    ("General Practitioner", "Healthcare", "HEALTH"),
    ("Surgeon", "Healthcare", "HEALTH"),
    ("Anesthesiologist", "Healthcare", "HEALTH"),
    ("Radiologist", "Healthcare", "HEALTH"),
    ("Cardiologist", "Healthcare", "HEALTH"),
    ("Neurologist", "Healthcare", "HEALTH"),
    ("Oncologist", "Healthcare", "HEALTH"),
    ("Pediatrician", "Healthcare", "HEALTH"),
    ("Psychiatrist", "Healthcare", "HEALTH"),
    ("Dermatologist", "Healthcare", "HEALTH"),
    ("Orthopedic Surgeon", "Healthcare", "HEALTH"),
    ("Plastic Surgeon", "Healthcare", "HEALTH"),
    ("Obstetrician/Gynecologist", "Healthcare", "HEALTH"),
    ("Ophthalmologist", "Healthcare", "HEALTH"),
    ("ENT Specialist", "Healthcare", "HEALTH"),
    ("Dentist", "Healthcare", "DENTAL"),
    ("Orthodontist", "Healthcare", "DENTAL"),
    ("Pharmacist", "Healthcare", "PHARMA"),
    ("Nurse", "Healthcare", "NURSING"),
    ("Nurse Practitioner", "Healthcare", "NURSING"),
    ("Nurse Anesthetist (CRNA)", "Healthcare", "NURSING"),
    ("Physician Assistant", "Healthcare", "HEALTH"),
    ("Physical Therapist", "Healthcare", "HEALTH"),
    ("Occupational Therapist", "Healthcare", "HEALTH"),
    ("Speech Therapist", "Healthcare", "HEALTH"),
    ("Psychologist", "Healthcare", "HEALTH"),
    ("Clinical Social Worker", "Healthcare", "HEALTH"),
    ("Veterinarian", "Healthcare", "HEALTH"),
    ("Medical Researcher", "Healthcare", "PHARMA"),
    ("Biomedical Scientist", "Healthcare", "PHARMA"),
    ("Genetic Counselor", "Healthcare", "HEALTH"),
    ("Radiologic Technologist", "Healthcare", "HEALTH"),
    ("Sonographer", "Healthcare", "HEALTH"),
    ("Paramedic", "Healthcare", "HEALTH"),
    ("Chiropractor", "Healthcare", "HEALTH"),
    ("Nutritionist/Dietitian", "Healthcare", "HEALTH"),
    ("Hospital Administrator", "Healthcare", "HEALTH"),
    ("Healthcare Consultant", "Healthcare", "HEALTH"),
    ("Civil Engineer", "Engineering", "ENGINEERING"),
    ("Structural Engineer", "Engineering", "ENGINEERING"),
    ("Mechanical Engineer", "Engineering", "ENGINEERING"),
    ("Electrical Engineer", "Engineering", "ENGINEERING"),
    ("Electronics Engineer", "Engineering", "ENGINEERING"),
    ("Chemical Engineer", "Engineering", "ENGINEERING"),
    ("Petroleum Engineer", "Engineering", "MINING_ENERGY"),
    ("Mining Engineer", "Engineering", "MINING_ENERGY"),
    ("Aerospace Engineer", "Engineering", "ENGINEERING"),
    ("Automotive Engineer", "Engineering", "ENGINEERING"),
    ("Marine Engineer", "Engineering", "MARITIME"),
    ("Industrial Engineer", "Engineering", "ENGINEERING"),
    ("Manufacturing Engineer", "Engineering", "ENGINEERING"),
    ("Materials Engineer", "Engineering", "ENGINEERING"),
    ("Environmental Engineer", "Engineering", "ENGINEERING"),
    ("Agricultural Engineer", "Engineering", "AGRICULTURE"),
    ("Biomedical Engineer", "Engineering", "ENGINEERING"),
    ("Nuclear Engineer", "Engineering", "MINING_ENERGY"),
    ("Energy Engineer", "Engineering", "MINING_ENERGY"),
    ("Renewable Energy Engineer", "Engineering", "MINING_ENERGY"),
    ("Mechatronics Engineer", "Engineering", "ENGINEERING"),
    ("Geotechnical Engineer", "Engineering", "ENGINEERING"),
    ("Surveyor", "Engineering", "ENGINEERING"),
    ("Construction Manager", "Construction", "ENGINEERING"),
    ("Project Engineer", "Engineering", "ENGINEERING"),
    ("Electrician", "Trades", "TRADES"),
    ("Plumber", "Trades", "TRADES"),
    ("HVAC Technician", "Trades", "TRADES"),
    ("Welder", "Trades", "TRADES"),
    ("Carpenter", "Trades", "TRADES"),
    ("Mason", "Trades", "TRADES"),
    ("Mechanic", "Trades", "TRADES"),
    ("Auto Electrician", "Trades", "TRADES"),
    ("CNC Machinist", "Trades", "TRADES"),
    ("Heavy Equipment Operator", "Trades", "TRADES"),
    ("Crane Operator", "Trades", "TRADES"),
    ("Commercial Pilot", "Aviation", "AVIATION"),
    ("Air Traffic Controller", "Aviation", "AVIATION"),
    ("Aircraft Maintenance Engineer", "Aviation", "AVIATION"),
    ("Ship Captain", "Maritime", "MARITIME"),
    ("Marine Officer", "Maritime", "MARITIME"),
    ("Merchant Navy Officer", "Maritime", "MARITIME"),
    ("Train Driver", "Transport", "LOGISTICS"),
    ("Truck Driver", "Transport", "LOGISTICS"),
    ("Diesel Mechanic", "Trades", "TRADES"),
    ("Solar Installer", "Trades", "TRADES"),
    ("Wind Turbine Technician", "Trades", "TRADES"),
    ("Elevator Technician", "Trades", "TRADES"),
    ("Locksmith", "Trades", "TRADES"),
    ("Chef", "Hospitality", "HOSPITALITY"),
    ("Baker", "Hospitality", "HOSPITALITY"),
    ("Butcher", "Trades", "TRADES"),
    ("Tailor/Fashion Designer", "Creative", "CREATIVE"),
    ("Hair Stylist", "Personal Services", "HOSPITALITY"),
    ("Beautician", "Personal Services", "HOSPITALITY"),
    ("Massage Therapist", "Personal Services", "HOSPITALITY"),
    ("Physicist", "Science", "SCIENCE"),
    ("Chemist", "Science", "SCIENCE"),
    ("Biologist", "Science", "SCIENCE"),
    ("Microbiologist", "Science", "SCIENCE"),
    ("Biochemist", "Science", "SCIENCE"),
    ("Biotechnologist", "Science", "SCIENCE"),
    ("Geologist", "Science", "MINING_ENERGY"),
    ("Geophysicist", "Science", "MINING_ENERGY"),
    ("Meteorologist", "Science", "SCIENCE"),
    ("Oceanographer", "Science", "SCIENCE"),
    ("Environmental Scientist", "Science", "SCIENCE"),
    ("Ecologist", "Science", "SCIENCE"),
    ("Astronomer", "Science", "SCIENCE"),
    ("Astrophysicist", "Science", "SCIENCE"),
    ("Statistician", "Science", "AI_DATA"),
    ("Mathematician", "Science", "SCIENCE"),
    ("Epidemiologist", "Science", "SCIENCE"),
    ("Pharmacologist", "Science", "PHARMA"),
    ("Toxicologist", "Science", "PHARMA"),
    ("Forensic Scientist", "Science", "SCIENCE"),
    ("Food Scientist", "Science", "SCIENCE"),
    ("Economist", "Science", "FINANCE"),
    ("University Professor", "Education", "EDU"),
    ("School Teacher", "Education", "EDU"),
    ("Principal/Headteacher", "Education", "EDU"),
    ("Education Consultant", "Education", "EDU"),
    ("Curriculum Developer", "Education", "EDU"),
    ("EdTech Specialist", "Education", "EDU"),
    ("Corporate Trainer", "Education", "EDU"),
    ("Special Education Teacher", "Education", "EDU"),
    ("ESL Teacher", "Education", "EDU"),
    ("Librarian", "Education", "EDU"),
    ("Academic Researcher", "Education", "EDU"),
    ("Civil Servant", "Government", "GOVT"),
    ("Diplomat", "Government", "GOVT"),
    ("Intelligence Analyst", "Government", "GOVT"),
    ("Police Officer", "Public Safety", "PUBLIC_SAFETY"),
    ("Detective", "Public Safety", "PUBLIC_SAFETY"),
    ("FBI/CIA/NSA Agent", "Government", "GOVT"),
    ("Military Officer", "Government", "GOVT"),
    ("Soldier", "Government", "GOVT"),
    ("Firefighter", "Public Safety", "PUBLIC_SAFETY"),
    ("Emergency Management Director", "Public Safety", "PUBLIC_SAFETY"),
    ("Policy Analyst", "Government", "GOVT"),
    ("Urban Planner", "Government", "GOVT"),
    ("Public Health Administrator", "Government", "GOVT"),
    ("Social Worker", "Government", "GOVT"),
    ("Customs Officer", "Government", "GOVT"),
    ("Border Patrol Agent", "Government", "GOVT"),
    ("Actor", "Media", "MEDIA"),
    ("Actress", "Media", "MEDIA"),
    ("Film Director", "Media", "MEDIA"),
    ("Producer", "Media", "MEDIA"),
    ("Screenwriter", "Media", "MEDIA"),
    ("Cinematographer", "Media", "MEDIA"),
    ("Film Editor", "Media", "MEDIA"),
    ("Music Producer", "Media", "MEDIA"),
    ("Singer/Musician", "Media", "MEDIA"),
    ("Composer", "Media", "MEDIA"),
    ("DJ", "Media", "MEDIA"),
    ("Dancer", "Media", "MEDIA"),
    ("Choreographer", "Media", "MEDIA"),
    ("Photographer", "Media", "CREATIVE"),
    ("Videographer", "Media", "CREATIVE"),
    ("Journalist", "Media", "MEDIA"),
    ("News Anchor", "Media", "MEDIA"),
    ("Radio Host", "Media", "MEDIA"),
    ("Podcast Host", "Media", "MEDIA"),
    ("Author/Writer", "Media", "MEDIA"),
    ("Editor", "Media", "MEDIA"),
    ("Publisher", "Media", "MEDIA"),
    ("YouTuber/Streamer", "Media", "MEDIA"),
    ("Fashion Designer", "Creative", "CREATIVE"),
    ("Interior Designer", "Creative", "CREATIVE"),
    ("Architect", "Creative", "CREATIVE"),
    ("Landscape Architect", "Creative", "CREATIVE"),
    ("Industrial Designer", "Creative", "CREATIVE"),
    ("Makeup Artist", "Creative", "CREATIVE"),
    ("Stunt Performer", "Media", "MEDIA"),
    ("Professional Athlete", "Sports", "SPORTS_GLOBAL"),
    ("Cricketer", "Sports", "CRICKET"),
    ("Footballer", "Sports", "FOOTBALL"),
    ("Basketball Player", "Sports", "SPORTS_GLOBAL"),
    ("Tennis Player", "Sports", "SPORTS_GLOBAL"),
    ("Golfer", "Sports", "SPORTS_GLOBAL"),
    ("Boxer/MMA Fighter", "Sports", "SPORTS_GLOBAL"),
    ("Olympic Athlete", "Sports", "SPORTS_GLOBAL"),
    ("Sports Coach", "Sports", "SPORTS_GLOBAL"),
    ("Fitness Trainer", "Sports", "SPORTS_GLOBAL"),
    ("Sports Manager", "Sports", "SPORTS_GLOBAL"),
    ("Sports Agent", "Sports", "SPORTS_GLOBAL"),
    ("Sports Analyst", "Sports", "SPORTS_GLOBAL"),
    ("Referee/Umpire", "Sports", "SPORTS_GLOBAL"),
    ("Esports Player", "Sports", "SPORTS_GLOBAL"),
    ("Esports Coach", "Sports", "SPORTS_GLOBAL"),
    ("Hotel Manager", "Hospitality", "HOSPITALITY"),
    ("Sommelier", "Hospitality", "HOSPITALITY"),
    ("Travel Agent", "Hospitality", "HOSPITALITY"),
    ("Tour Operator", "Hospitality", "HOSPITALITY"),
    ("Event Planner", "Hospitality", "HOSPITALITY"),
    ("Wedding Planner", "Hospitality", "HOSPITALITY"),
    ("Flight Attendant", "Hospitality", "HOSPITALITY"),
    ("Cruise Ship Director", "Hospitality", "HOSPITALITY"),
    ("Restaurant Owner", "Hospitality", "HOSPITALITY"),
    ("Café Owner", "Hospitality", "HOSPITALITY"),
    ("Bar Manager", "Hospitality", "HOSPITALITY"),
    ("Casino Manager", "Hospitality", "HOSPITALITY"),
    ("Theme Park Manager", "Hospitality", "HOSPITALITY"),
    ("Farmer", "Agriculture", "AGRICULTURE"),
    ("Agronomist", "Agriculture", "AGRICULTURE"),
    ("Agricultural Scientist", "Agriculture", "AGRICULTURE"),
    ("Horticulturist", "Agriculture", "AGRICULTURE"),
    ("Animal Scientist", "Agriculture", "AGRICULTURE"),
    ("Forester", "Environment", "AGRICULTURE"),
    ("Fisheries Manager", "Environment", "AGRICULTURE"),
    ("Environmental Consultant", "Environment", "SCIENCE"),
    ("Conservation Scientist", "Environment", "SCIENCE"),
    ("Wildlife Biologist", "Environment", "SCIENCE"),
    ("Sustainability Manager", "Environment", "BUSINESS"),
    ("Renewable Energy Consultant", "Environment", "MINING_ENERGY"),
    ("Waste Management Specialist", "Environment", "SCIENCE"),
    ("Water Resource Engineer", "Environment", "ENGINEERING"),
    ("Warehouse Manager", "Logistics", "LOGISTICS"),
    ("Fleet Manager", "Logistics", "LOGISTICS"),
    ("Customs Broker", "Logistics", "LOGISTICS"),
    ("Freight Forwarder", "Logistics", "LOGISTICS"),
    ("Air Cargo Manager", "Logistics", "LOGISTICS"),
    ("Port Manager", "Logistics", "LOGISTICS"),
    ("Railway Manager", "Logistics", "LOGISTICS"),
    ("Urban Transit Manager", "Logistics", "LOGISTICS"),
    ("Supply Chain Analyst", "Logistics", "LOGISTICS"),
    ("Distribution Manager", "Logistics", "LOGISTICS"),
    ("Consultant", "Business", "BUSINESS"),
    ("Freelancer", "Business", "ENTREPRENEUR"),
    ("Investor", "Finance", "FINANCE"),
    ("Landlord", "Real Estate", "REAL_ESTATE"),
    ("Nonprofit Director", "Business", "BUSINESS"),
    ("NGO Manager", "Business", "BUSINESS"),
    ("Religious Leader", "Community", "DEFAULT"),
    ("Life Coach", "Coaching", "BUSINESS"),
    ("Business Coach", "Coaching", "BUSINESS"),
    ("Career Coach", "Coaching", "BUSINESS"),
    ("Relationship Coach", "Coaching", "BUSINESS"),
    ("Wellness Coach", "Coaching", "BUSINESS"),
    ("Digital Nomad", "Business", "ENTREPRENEUR"),
    ("Dropshipper", "Business", "ENTREPRENEUR"),
    ("Print on Demand Seller", "Business", "ENTREPRENEUR"),
    ("Virtual Assistant", "Business", "BUSINESS"),
    ("Translator/Interpreter", "Language", "DEFAULT"),
    ("Sign Language Interpreter", "Language", "DEFAULT"),
    ("Fashion Model", "Creative", "CREATIVE"),
    ("Professional Gamer", "Esports", "SPORTS_GLOBAL"),
    ("Esports Streamer", "Esports", "SPORTS_GLOBAL"),
    ("Pet Groomer", "Personal Services", "HOSPITALITY"),
    ("Dog Trainer", "Personal Services", "HOSPITALITY"),
    ("Event Photographer", "Creative", "CREATIVE"),
    ("Drone Pilot", "Aviation", "AVIATION"),
]

# Hardware-like detail templates per category. Every career in the catalog is
# enriched from these so the list is fully browsable (skills, subjects, degrees,
# industries, salary, outlook) even though it contains hundreds of roles.
CATEGORY_DETAILS: dict[str, dict] = {
    "Technology": {
        "emoji": "💻",
        "skills": ["programming", "problem solving", "analytical thinking", "learning agility", "attention to detail", "collaboration"],
        "subjects": ["computer science", "mathematics", "physics"],
        "degrees": ["Computer Science", "Software Engineering", "Information Technology", "Maths"],
        "industries": ["Technology", "Fintech", "E-commerce", "Healthcare", "Startups"],
        "future_paths": ["Senior Engineer", "Tech Lead", "Solutions Architect", "CTO"],
        "salary": "$90k - $180k (India: ₹18-60L)",
        "outlook": "Very strong — technology talent stays in permanent demand.",
    },
    "Creative": {
        "emoji": "🎨",
        "skills": ["creativity", "visual thinking", "communication", "attention to detail", "craft", "curiosity"],
        "subjects": ["art", "design", "media", "psychology"],
        "degrees": ["Design", "Visual Arts", "Media", "Fine Arts"],
        "industries": ["Design studios", "Media", "Technology", "Advertising", "Film"],
        "future_paths": ["Senior Designer", "Creative Director", "Art Director", "Own studio"],
        "salary": "$60k - $140k (India: ₹8-35L)",
        "outlook": "Strong — craft and aesthetics increasingly decide products.",
    },
    "Marketing": {
        "emoji": "📣",
        "skills": ["creativity", "copywriting", "data analysis", "psychology", "communication", "strategy"],
        "subjects": ["business", "psychology", "economics", "media"],
        "degrees": ["Marketing", "Business", "Media", "Psychology"],
        "industries": ["E-commerce", "Technology", "Consumer brands", "Agencies"],
        "future_paths": ["Growth Lead", "Brand Manager", "CMO", "Marketing Consultant"],
        "salary": "$70k - $150k (India: ₹8-35L)",
        "outlook": "Strong — every brand now lives online.",
    },
    "Media": {
        "emoji": "🎬",
        "skills": ["creativity", "communication", "storytelling", "writing", "persistence", "public speaking"],
        "subjects": ["media", "english", "history", "performing arts"],
        "degrees": ["Media", "Journalism", "Communications", "Film"],
        "industries": ["Entertainment", "Broadcast", "Publishing", "Digital media", "Advertising"],
        "future_paths": ["Director", "Executive Producer", "Editor-in-Chief", "Media Founder"],
        "salary": "$50k - $150k (India: ₹6-40L)",
        "outlook": "Evolving — bold storytellers remain highly valued.",
    },
    "Business": {
        "emoji": "📊",
        "skills": ["leadership", "communication", "strategy", "analytical thinking", "negotiation", "resilience"],
        "subjects": ["business", "economics", "accounting", "mathematics"],
        "degrees": ["Business", "Economics", "MBA", "Commerce"],
        "industries": ["Consulting", "Banking", "Technology", "Retail", "Every industry"],
        "future_paths": ["Director", "VP", "COO", "CEO / Founder"],
        "salary": "$80k - $200k+ (India: ₹15-80L)",
        "outlook": "Steady — strong operators never go out of demand.",
    },
    "Finance": {
        "emoji": "💹",
        "skills": ["analytical thinking", "mathematics", "financial modelling", "attention to detail", "risk management", "communication"],
        "subjects": ["mathematics", "economics", "accounting", "business"],
        "degrees": ["Finance", "Economics", "Accounting", "Business", "Mathematics"],
        "industries": ["Banking", "Investments", "Consulting", "Corporate finance", "Insurance"],
        "future_paths": ["Senior Analyst", "Portfolio Manager", "MD", "CFO / CIO"],
        "salary": "$90k - $250k+ (India: ₹15-100L)",
        "outlook": "Strong — money always needs sharp minds.",
    },
    "Law": {
        "emoji": "⚖️",
        "skills": ["critical thinking", "communication", "research", "persuasion", "attention to detail", "ethics"],
        "subjects": ["history", "political science", "english", "economics"],
        "degrees": ["Law (LLB / JD)", "Law + specialisations"],
        "industries": ["Law firms", "Courts", "Corporate", "Government", "NGOs"],
        "future_paths": ["Senior Associate", "Partner", "Judge", "General Counsel"],
        "salary": "$90k - $250k (India: ₹8-60L)",
        "outlook": "Steady — law grows with the complexity of the world.",
    },
    "Healthcare": {
        "emoji": "🩺",
        "skills": ["empathy", "problem solving", "communication", "resilience", "attention to detail", "science literacy"],
        "subjects": ["biology", "chemistry", "physics", "mathematics"],
        "degrees": ["Medicine (MBBS/MD)", "Nursing", "Allied Health", "Biomedical Science"],
        "industries": ["Hospitals", "Clinics", "Research", "Public health", "Pharma"],
        "future_paths": ["Specialist", "Consultant", "Hospital leader", "Medical researcher"],
        "salary": "$80k - $300k+ (India: ₹8-80L)",
        "outlook": "Durable — healthcare demand only grows.",
    },
    "Engineering": {
        "emoji": "🛠️",
        "skills": ["mathematics", "physics", "problem solving", "design thinking", "project management", "attention to detail"],
        "subjects": ["mathematics", "physics", "chemistry"],
        "degrees": ["Mechanical Engineering", "Civil Engineering", "Electrical Engineering", "Chemical Engineering"],
        "industries": ["Construction", "Manufacturing", "Energy", "Automotive", "Aerospace", "Technology"],
        "future_paths": ["Senior Engineer", "Project Manager", "Technical Director", "Principal Engineer"],
        "salary": "$80k - $180k (India: ₹9-40L)",
        "outlook": "Steady — infrastructure and industry are permanent needs.",
    },
    "Trades": {
        "emoji": "🔧",
        "skills": ["hands-on craft", "problem solving", "precision", "physical fitness", "reliability", "customer service"],
        "subjects": ["mathematics", "physics", "trade school / apprenticeship", "engineering technology"],
        "degrees": ["Apprenticeship", "Vocational diploma", "Trade certification"],
        "industries": ["Construction", "Manufacturing", "Energy", "Property services"],
        "future_paths": ["Master tradesperson", "Site supervisor", "Business owner", "Licensed contractor"],
        "salary": "$55k - $130k (India: ₹4-20L)",
        "outlook": "Very strong — skilled trades face global shortages.",
    },
    "Aviation": {
        "emoji": "✈️",
        "skills": ["precision", "decision making", "communication", "attention to detail", "stress management", "physics"],
        "subjects": ["mathematics", "physics", "geography", "english"],
        "degrees": ["Aviation", "Aeronautical Engineering", "Flight training (CPL/ATPL)"],
        "industries": ["Airlines", "Aviation services", "Defence", "Logistics"],
        "future_paths": ["Senior Captain", "Flight Instructor", "Airline management", "Aviation regulator"],
        "salary": "$60k - $250k (India: ₹10-90L)",
        "outlook": "Steady and recovering strongly — air travel always expands.",
    },
    "Maritime": {
        "emoji": "🚢",
        "skills": ["navigation", "leadership", "resilience", "problem solving", "seamanship", "engineering"],
        "subjects": ["mathematics", "physics", "geography", "mechanical science"],
        "degrees": ["Nautical Science", "Marine Engineering", "Maritime Studies"],
        "industries": ["Shipping", "Ports", "Cruise", "Offshore", "Logistics"],
        "future_paths": ["Captain", "Chief Engineer", "Marine Superintendent", "Port executive"],
        "salary": "$60k - $200k (India: ₹10-60L)",
        "outlook": "Strong — 90% of world trade moves by sea.",
    },
    "Science": {
        "emoji": "🔬",
        "skills": ["curiosity", "critical thinking", "experimentation", "mathematics", "data analysis", "writing"],
        "subjects": ["biology", "chemistry", "physics", "mathematics"],
        "degrees": ["BSc / MSc / PhD in a science", "Biotechnology", "Data Science"],
        "industries": ["Universities", "Research labs", "Pharma", "Biotech", "Government"],
        "future_paths": ["Principal Investigator", "Head of Research", "Chief Scientist", "Professor"],
        "salary": "$70k - $200k (India: ₹8-45L)",
        "outlook": "Steady in academia; booming in biotech and AI.",
    },
    "Education": {
        "emoji": "🍎",
        "skills": ["communication", "empathy", "patience", "creativity", "leadership", "public speaking"],
        "subjects": ["education", "english", "psychology", "your favourite subject"],
        "degrees": ["Education", "Subject degree + teaching qualification"],
        "industries": ["Schools", "EdTech", "Tutoring", "Training", "Content"],
        "future_paths": ["Lead Teacher", "Curriculum Designer", "Principal", "EdTech Founder"],
        "salary": "$50k - $120k (India: ₹5-25L)",
        "outlook": "Stable — and expanding fast through EdTech.",
    },
    "Government": {
        "emoji": "🏛️",
        "skills": ["analysis", "policy thinking", "communication", "ethics", "writing", "resilience"],
        "subjects": ["political science", "history", "economics", "public policy"],
        "degrees": ["Public Policy", "Political Science", "Law", "Economics", "International Relations"],
        "industries": ["Government", "Diplomacy", "Public sector", "International bodies", "NGOs"],
        "future_paths": ["Senior civil servant", "Directorate", "Diplomat", "Elected office"],
        "salary": "$60k - $160k (India: ₹6-30L)",
        "outlook": "Stable and competitive — high entry bars, strong security.",
    },
    "Public Safety": {
        "emoji": "🚓",
        "skills": ["bravery", "decision making", "communication", "physical fitness", "integrity", "teamwork"],
        "subjects": ["physical education", "law", "psychology", "first aid"],
        "degrees": ["Criminology", "Law enforcement academy", "Physical training", "Emergency management"],
        "industries": ["Police", "Fire services", "Defence", "Emergency response", "Security"],
        "future_paths": ["Sergeant", "Captain / Chief", "Investigative lead", "Emergency director"],
        "salary": "$55k - $140k (India: ₹5-25L)",
        "outlook": "Stable — safety is a permanent public priority.",
    },
    "Sports": {
        "emoji": "🏅",
        "skills": ["competitiveness", "dedication", "teamwork", "coordination", "coaching", "discipline"],
        "subjects": ["physical education", "biology", "nutrition", "sport management"],
        "degrees": ["Any degree via scholarships", "Sports Science", "Sports Management"],
        "industries": ["Pro sports", "Leagues", "Sponsorship", "Media", "Fitness"],
        "future_paths": ["Pro career", "Captain", "Coach", "Agent", "Sports executive"],
        "salary": "$40k - $100M+ for elite (India: ₹10L-100Cr+)",
        "outlook": "Highly selective; the ecosystem around it is booming.",
    },
    "Hospitality": {
        "emoji": "🍽️",
        "skills": ["service mindset", "communication", "multitasking", "organisation", "hospitality craft", "business sense"],
        "subjects": ["business", "food & nutrition", "languages", "hotel management"],
        "degrees": ["Hotel Management", "Culinary Arts", "Hospitality Business"],
        "industries": ["Hotels", "Restaurants", "Cruise", "Events", "Airlines"],
        "future_paths": ["Manager", "Director", "General Manager", "Owner"],
        "salary": "$45k - $120k (India: ₹4-25L)",
        "outlook": "Strong in tourist economies — Australia and the Gulf especially.",
    },
    "Agriculture": {
        "emoji": "🌾",
        "skills": ["plant & animal science", "data analysis", "sustainability", "business", "problem solving", "outdoor work"],
        "subjects": ["biology", "chemistry", "economics", "environmental science"],
        "degrees": ["Agricultural Science", "Agribusiness", "Horticulture", "Food Science"],
        "industries": ["Farming", "Agri-tech", "Food", "Environment", "Government"],
        "future_paths": ["Farm manager", "Agronomist", "Agri-tech founder", "R&D scientist"],
        "salary": "$50k - $130k (India: ₹5-20L)",
        "outlook": "Growing — the world needs more food, more sustainably.",
    },
    "Environment": {
        "emoji": "🌱",
        "skills": ["environmental science", "data analysis", "policy", "communication", "systems thinking", "field work"],
        "subjects": ["environmental science", "biology", "chemistry", "geography"],
        "degrees": ["Environmental Science", "Sustainability", "Ecology", "Climate Science"],
        "industries": ["Consulting", "Government", "NGOs", "Energy", "Corporate sustainability"],
        "future_paths": ["Sustainability Lead", "Environmental Director", "Climate advisor", "Founder"],
        "salary": "$55k - $140k (India: ₹6-25L)",
        "outlook": "Rapidly growing — sustainability is now mandatory everywhere.",
    },
    "Logistics": {
        "emoji": "📦",
        "skills": ["planning", "data analysis", "coordination", "problem solving", "negotiation", "operations"],
        "subjects": ["mathematics", "business", "supply chain", "information systems"],
        "degrees": ["Supply Chain Management", "Logistics", "Business", "Industrial Engineering"],
        "industries": ["E-commerce", "Shipping", "Retail", "Manufacturing", "Ports & freight"],
        "future_paths": ["Supply Chain Director", "Operations VP", "Head of Logistics", "Fleet Owner"],
        "salary": "$60k - $150k (India: ₹6-30L)",
        "outlook": "Strong — global trade and e-commerce keep it essential.",
    },
    "Real Estate": {
        "emoji": "🏠",
        "skills": ["negotiation", "sales", "market analysis", "networking", "property law", "finance"],
        "subjects": ["business", "economics", "finance", "construction"],
        "degrees": ["Real Estate", "Business", "Finance", "Urban Planning"],
        "industries": ["Property", "Construction", "Finance", "Urban development"],
        "future_paths": ["Senior agent", "Broker", "Developer", "Portfolio owner"],
        "salary": "$60k - $250k+ commission-driven (India: ₹6-60L)",
        "outlook": "Cyclical but strong — property is a core asset class.",
    },
    "Esports": {
        "emoji": "🎮",
        "skills": ["reaction speed", "strategy", "teamwork", "game sense", "content creation", "discipline"],
        "subjects": ["computer science", "media", "marketing"],
        "degrees": ["Game design", "Esports Management", "Media", "Computing"],
        "industries": ["Esports orgs", "Gaming", "Streaming", "Sponsorship", "Event production"],
        "future_paths": ["Pro player", "Coach", "Team manager", "Streamer", "Event organiser"],
        "salary": "$30k - $10M+ for top players (India: ₹5L-30Cr+)",
        "outlook": "Booming — competitive gaming is a global industry.",
    },
    "Coaching": {
        "emoji": "🗣️",
        "skills": ["active listening", "communication", "empathy", "accountability", "persuasion", "niche expertise"],
        "subjects": ["psychology", "business", "communication"],
        "degrees": ["Psychology", "Coaching certification", "Business", "Any + life experience"],
        "industries": ["Self-employed", "Consulting", "Online courses", "Corporate training"],
        "future_paths": ["Master coach", "Author", "Course creator", "Practice owner"],
        "salary": "$50k - $250k (India: ₹8-60L)",
        "outlook": "Growing — people happily invest in their potential.",
    },
    "Language": {
        "emoji": "🗣️",
        "skills": ["language mastery", "cultural awareness", "writing", "listening", "precision", "patience"],
        "subjects": ["languages", "linguistics", "literature", "media"],
        "degrees": ["Linguistics", "Languages", "Translation", "Interpreting"],
        "industries": ["Translated media", "International business", "Government", "Tourism"],
        "future_paths": ["Lead interpreter", "Localisation lead", "Languages professor", "Global consultant"],
        "salary": "$50k - $120k (India: ₹5-20L)",
        "outlook": "Steady — multilingual talent is always rare.",
    },
    "Personal Services": {
        "emoji": "💆",
        "skills": ["craft", "customer service", "attention to detail", "business sense", "empathy", "consistency"],
        "subjects": ["biology", "business", "beauty & wellness courses"],
        "degrees": ["Vocational training", "Beauty / wellness certification", "Business"],
        "industries": ["Salons", "Spas", "Self-employed", "Wellness brands"],
        "future_paths": ["Lead stylist", "Studio owner", "Franchise owner", "Brand founder"],
        "salary": "$40k - $100k (India: ₹3-15L)",
        "outlook": "Steady — personal care is a durable spending category.",
    },
    "Community": {
        "emoji": "🤝",
        "skills": ["leadership", "communication", "empathy", "public speaking", "organisation", "service"],
        "subjects": ["philosophy", "psychology", "history", "community studies"],
        "degrees": ["Theology", "Community leadership", "Social work", "Any degree"],
        "industries": ["Religious organisations", "Community centres", "NGOs", "Social enterprise"],
        "future_paths": ["Community leader", "Social entrepreneur", "Director of programs", "Counsellor"],
        "salary": "$40k - $100k (India: ₹4-15L)",
        "outlook": "Stable — communities always need leaders and counsellors.",
    },
    "Construction": {
        "emoji": "🏗️",
        "skills": ["project management", "leadership", "scheduling", "budgeting", "safety", "negotiation"],
        "subjects": ["mathematics", "physics", "construction management", "architecture"],
        "degrees": ["Construction Management", "Civil Engineering", "Project Management"],
        "industries": ["Construction", "Real Estate", "Infrastructure", "Government"],
        "future_paths": ["Project Manager", "Construction Director", "Developer", "Owner"],
        "salary": "$70k - $160k (India: ₹8-35L)",
        "outlook": "Steady — building never stops.",
    },
    "Transport": {
        "emoji": "🚛",
        "skills": ["safety", "responsibility", "spatial awareness", "reliability", "route planning", "customer service"],
        "subjects": ["mathematics", "geography", "driving / vocational training"],
        "degrees": ["Vocational licence", "Transport management", "Logistics"],
        "industries": ["Freight", "Public transport", "Delivery", "Logistics"],
        "future_paths": ["Lead driver", "Fleet supervisor", "Dispatcher", "Transport manager"],
        "salary": "$45k - $110k (India: ₹4-18L)",
        "outlook": "Stable — goods and people always need moving.",
    },
    "DEFAULT": {
        "emoji": "💼",
        "skills": ["communication", "problem solving", "learning agility", "reliability", "teamwork", "adaptability"],
        "subjects": ["english", "mathematics", "your best subject"],
        "degrees": ["Any degree relevant to the field", "Diploma / certification"],
        "industries": ["Varies by field", "Private sector", "Public sector"],
        "future_paths": ["Senior role", "Manager", "Specialist", "Independent expert"],
        "salary": "$50k - $150k (India: ₹5-40L)",
        "outlook": "Steady — strong performers always find opportunity.",
    },
}


def slugify(title: str) -> str:
    """slug for a career title (stable, unique within the catalog)."""
    s = title.lower().strip()
    for a, b in (("&", "and"), ("/", " or "), ("(", ""), (")", "")):
        s = s.replace(a, b)
    return "-".join([w for w in s.replace("'", "").split() if w])


_CASE_MAP = {
    "business": "Business",
    "design": "Design",
    "education": "Education",
    "engineering": "Engineering",
    "entrepreneurship": "Entrepreneurship",
    "finance": "Finance",
    "law": "Law",
    "media": "Media",
    "medicine": "Medicine",
    "psychology": "Psychology",
    "science": "Science",
    "technology": "Technology",
}


def normalize_category(category: str | None) -> str:
    """Canonical Title-Case label for a category (dedupes case variants)."""
    if not category:
        return "Other"
    key = category.lower().strip()
    return _CASE_MAP.get(key, category.strip())


def build_career(title: str, category: str, profile: str) -> dict:
    """Enrich a catalog row into a full Career-compatible dict."""
    category = normalize_category(category)
    detail = CATEGORY_DETAILS.get(category, CATEGORY_DETAILS["DEFAULT"])
    countries = RANKING_PROFILES.get(profile, RANKING_PROFILES["DEFAULT"])
    return {
        "slug": slugify(title),
        "title": title,
        "category": category,
        "emoji": detail["emoji"],
        "summary": f"{title} — a career in {category.lower()} that rewards {detail['skills'][0]} and {detail['skills'][1]}.",
        "description": (
            f"As a {title.lower()}, you focus on {detail['skills'][2]} and {detail['skills'][3]} to deliver real outcomes "
            f"in the {category.lower()} space. You learn by doing, adapt fast and build skills that compound over time."
        ),
        "what_they_do": (
            f"You solve problems, work closely with people and teams, and improve every day. "
            f"Day to day this involves {detail['skills'][4]}, {detail['skills'][5]} and constant learning."
        ),
        "skills": detail["skills"],
        "subjects": detail["subjects"],
        "degrees": detail["degrees"],
        "industries": detail["industries"],
        "future_paths": detail["future_paths"],
        "salary_range": detail["salary"],
        "outlook": detail["outlook"],
        "ranking_profile": profile,
        "country_rankings": countries,
    }