"""Seed catalog data for the NOVI platform (careers + universities).

Idempotent: only inserts rows when the tables are empty.
"""

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.career import Career
from app.models.university import University
from app.db.career_catalog import CAREERS as CAREERS_TUPLES
from app.db.career_catalog import RANKING_PROFILES, build_career, normalize_category, slugify


def _detailed_careers() -> list[dict]:
    """Hand-written flagship entries (richer than the catalog defaults).
    These take priority over catalog-generated rows with the same slug."""
    return [
    {
        "slug": "product-manager",
        "title": "Product Manager",
        "category": "technology",
        "emoji": "🧭",
        "summary": "Brings technology, business and people together to create products that solve real problems.",
        "description": "Product Managers decide WHAT to build and WHY. They talk to users, spot problems, work with designers and engineers, and turn ideas into products people actually love.",
        "what_they_do": "Talk to users to find what they need. Prioritize features. Write clear specs. Coordinate engineers and designers. Measure whether a product is working and iterate.",
        "skills": ["communication", "problem solving", "leadership", "analytical thinking", "creativity", "empathy"],
        "subjects": ["computer science", "business", "psychology", "economics", "mathematics"],
        "degrees": ["Computer Science", "Business / MBA", "Engineering", "Psychology", "Design"],
        "industries": ["Technology", "Fintech", "E-commerce", "Healthcare", "SaaS"],
        "future_paths": ["VP of Product", "Founder / CEO", "Product Director", "Startup Product Lead"],
        "salary_range": "$120k - $180k (India: ₹25-60L)",
        "outlook": "Very strong — every company building software wants product leaders.",
    },
    {
        "slug": "ai-engineer",
        "title": "AI Engineer",
        "category": "technology",
        "emoji": "🤖",
        "summary": "Builds intelligent systems — chatbots, recommendation engines, self-driving tech.",
        "description": "AI Engineers turn machine learning research into systems people use every day. You train models, build the software around them, and make AI reliable, fast and safe.",
        "what_they_do": "Design and train ML models. Build APIs to serve them. Collect and clean data. Improve accuracy and latency. Deploy and monitor models in production.",
        "skills": ["programming", "mathematics", "problem solving", "statistics", "machine learning", "data engineering"],
        "subjects": ["computer science", "mathematics", "statistics", "physics"],
        "degrees": ["Computer Science", "AI / ML", "Mathematics", "Data Science"],
        "industries": ["Technology", "Autonomous vehicles", "Healthcare", "Finance", "Robotics"],
        "future_paths": ["ML Engineer", "Research Scientist", "AI Architect", "Founder"],
        "salary_range": "$140k - $220k (India: ₹30-70L)",
        "outlook": "Explosive growth — AI is now the default layer of every product.",
    },
    {
        "slug": "software-engineer",
        "title": "Software Engineer",
        "category": "technology",
        "emoji": "💻",
        "summary": "Designs, builds and ships the apps, websites and systems the world runs on.",
        "description": "Software Engineers write the code behind apps, websites and platforms. You solve problems by building — debugging, designing systems and turning requirements into working software.",
        "what_they_do": "Write and review code. Design systems that scale. Debug issues. Automate workflows. Collaborate with product and design on features.",
        "skills": ["programming", "problem solving", "logical thinking", "attention to detail", "collaboration", "system design"],
        "subjects": ["computer science", "mathematics", "physics"],
        "degrees": ["Computer Science", "Software Engineering", "Information Technology"],
        "industries": ["Technology", "Banking", "Gaming", "Transport", "Every industry"],
        "future_paths": ["Senior Engineer", "Tech Lead", "Engineering Manager", "Solutions Architect"],
        "salary_range": "$100k - $170k (India: ₹20-50L)",
        "outlook": "Consistently high demand forever.",
    },
    {
        "slug": "cybersecurity-analyst",
        "title": "Cybersecurity Analyst",
        "category": "technology",
        "emoji": "🛡️",
        "summary": "Protects systems and people from hackers, breaches and digital threats.",
        "description": "Cybersecurity Analysts defend organizations against attacks. You monitor systems, investigate incidents, test defences and build the security that keeps data safe.",
        "what_they_do": "Monitor networks for threats. Investigate security incidents. Run penetration tests. Manage firewalls and detection tools. Educate teams on safe practices.",
        "skills": ["attention to detail", "problem solving", "networking", "programming", "ethical hacking", "curiosity"],
        "subjects": ["computer science", "mathematics"],
        "degrees": ["Cybersecurity", "Computer Science", "Information Security"],
        "industries": ["Technology", "Banking", "Government", "Healthcare", "Defence"],
        "future_paths": ["Security Engineer", "Penetration Tester", "CISO", "Security Architect"],
        "salary_range": "$100k - $160k (India: ₹15-40L)",
        "outlook": "Critical workforce shortage — strong and growing demand.",
    },
    {
        "slug": "data-scientist",
        "title": "Data Scientist",
        "category": "technology",
        "emoji": "📊",
        "summary": "Turns data into answers — what will customers want, what should a company do next.",
        "description": "Data Scientists find stories hidden inside data. You clean it, explore it, build models to predict the future, and explain what it all means to decision-makers.",
        "what_they_do": "Analyze data to find insights. Build predictive models. Run experiments (A/B tests). Visualize findings. Communicate recommendations to business teams.",
        "skills": ["statistics", "programming", "curiosity", "communication", "machine learning", "critical thinking"],
        "subjects": ["mathematics", "statistics", "computer science", "economics"],
        "degrees": ["Data Science", "Statistics", "Computer Science", "Economics / Mathematics"],
        "industries": ["Technology", "E-commerce", "Finance", "Healthcare", "Marketing"],
        "future_paths": ["Senior Data Scientist", "ML Engineer", "Data Science Manager", "Analytics Leader"],
        "salary_range": "$120k - $190k (India: ₹20-55L)",
        "outlook": "Very strong — every organization is becoming data-driven.",
    },
    {
        "slug": "game-developer",
        "title": "Game Developer",
        "category": "media",
        "emoji": "🎮",
        "summary": "Builds the worlds, mechanics and stories inside video games.",
        "description": "Game Developers bring games to life with code, art and design. You build gameplay systems, graphics engines and the interactive experiences millions of people play.",
        "what_they_do": "Implement gameplay mechanics. Work with designers and artists. Optimize for performance. Write shaders and physics systems. Test and polish the player experience.",
        "skills": ["programming", "creativity", "problem solving", "game design", "mathematics", "collaboration"],
        "subjects": ["computer science", "mathematics", "art", "physics"],
        "degrees": ["Computer Science", "Game Development", "Digital Media", "Computer Graphics"],
        "industries": ["Gaming", "Entertainment", "EdTech", "Simulation"],
        "future_paths": ["Senior Game Engineer", "Technical Director", "Lead Designer", "Indie Game Founder"],
        "salary_range": "$90k - $160k (India: ₹15-40L)",
        "outlook": "Strong — gaming is bigger than film and music combined.",
    },
    {
        "slug": "ux-designer",
        "title": "UX Designer",
        "category": "design",
        "emoji": "🎨",
        "summary": "Designs apps and websites that are easy and delightful — not just pretty.",
        "description": "UX Designers make products feel intuitive. You research how people think and behave, sketch interfaces, test designs and refine until a product feels effortless.",
        "what_they_do": "User research and interviews. Wireframes and prototypes. Usability testing. Design systems. Collaborating with engineers on the final experience.",
        "skills": ["empathy", "creativity", "communication", "research", "prototyping", "attention to detail"],
        "subjects": ["art", "psychology", "computer science", "design"],
        "degrees": ["Design", "Psychology", "Human-Computer Interaction", "Fine Arts"],
        "industries": ["Technology", "E-commerce", "Banking", "EdTech", "Healthcare"],
        "future_paths": ["Senior UX Designer", "Product Design Lead", "Design Manager", "Design Director"],
        "salary_range": "$100k - $160k (India: ₹18-45L)",
        "outlook": "Strong — great user experience is now a competitive advantage.",
    },
    {
        "slug": "product-designer",
        "title": "Product Designer",
        "category": "design",
        "emoji": "🛠️",
        "summary": "Shapes both how a product looks AND how it works end-to-end.",
        "description": "Product Designers own the full design of a product — research, UI, interaction and brand. It's UX + visual design + a deep focus on the product being useful and loved.",
        "what_they_do": "Define the product experience. Design interfaces and interactions. Prototype and test. Maintain a design system. Partner closely with PMs and engineers.",
        "skills": ["creativity", "empathy", "prototyping", "systems thinking", "communication", "visual design"],
        "subjects": ["design", "art", "psychology", "computer science"],
        "degrees": ["Product Design", "Interaction Design", "HCI", "Visual Communication"],
        "industries": ["Technology", "Startups", "Consumer apps", "Fintech", "Gaming"],
        "future_paths": ["Senior Product Designer", "Design Lead", "Head of Design", "Product Manager"],
        "salary_range": "$110k - $170k (India: ₹20-50L)",
        "outlook": "Strong — products win on craft.",
    },
    {
        "slug": "architect",
        "title": "Architect",
        "category": "design",
        "emoji": "🏛️",
        "summary": "Designs buildings and spaces that shape how people live, work and feel.",
        "description": "Architects design buildings — balancing beauty, function, safety, sustainability and cost. You create drawings, models and technical plans that become places people use daily.",
        "what_they_do": "Design building concepts. Create technical drawings and 3D models. Choose materials and layouts. Manage projects with engineers and clients. Ensure safety and code compliance.",
        "skills": ["creativity", "spatial thinking", "mathematics", "attention to detail", "communication", "project management"],
        "subjects": ["mathematics", "physics", "art", "design"],
        "degrees": ["Architecture", "Civil Engineering"],
        "industries": ["Construction", "Real Estate", "Urban Design", "Interior Design"],
        "future_paths": ["Senior Architect", "Design Principal", "Urban Planner", "Own Architecture Firm"],
        "salary_range": "$90k - $160k (India: ₹12-35L)",
        "outlook": "Steady — cities and infrastructure always need good designers.",
    },
    {
        "slug": "entrepreneur",
        "title": "Entrepreneur / Founder",
        "category": "entrepreneurship",
        "emoji": "🚀",
        "summary": "Builds companies from an idea — owning the vision, risk and reward.",
        "description": "Entrepreneurs create companies. You identify a problem, build a solution, find customers and grow a business — wearing many hats and learning constantly.",
        "what_they_do": "Find customer problems. Validate ideas. Build an MVP. Raise money or bootstrap. Hire a team. Sell, market and iterate faster than anyone else can.",
        "skills": ["risk-taking", "resilience", "communication", "sales", "creativity", "leadership", "problem solving"],
        "subjects": ["business", "economics", "computer science", "psychology"],
        "degrees": ["Business / MBA", "Computer Science", "Engineering", "Any degree + hustle"],
        "industries": ["Startups", "Technology", "E-commerce", "Every industry"],
        "future_paths": ["Scale a company", "Investor / Venture Capital", "Serial Founder", "Intrapreneur / Exec"],
        "salary_range": "$0 to unlimited (equity-driven)",
        "outlook": "High risk, high reward — the skills transfer into everything.",
    },
    {
        "slug": "business-analyst",
        "title": "Business Analyst",
        "category": "business",
        "emoji": "📈",
        "summary": "Translates business problems into solutions — the bridge between people and systems.",
        "description": "Business Analysts figure out how organizations can work better. You study processes, talk to stakeholders, analyze data and define exactly what should change.",
        "what_they_do": "Analyze business processes. Gather requirements from stakeholders. Model and document solutions. Help choose software and tools. Measure results after changes.",
        "skills": ["analytical thinking", "communication", "problem solving", "data analysis", "documentation", "stakeholder management"],
        "subjects": ["business", "economics", "mathematics", "computer science"],
        "degrees": ["Business", "Economics", "Information Systems", "Commerce"],
        "industries": ["Banking", "Consulting", "Technology", "Retail", "Government"],
        "future_paths": ["Senior Business Analyst", "Product Manager", "Consultant", "Program Manager"],
        "salary_range": "$90k - $140k (India: ₹12-30L)",
        "outlook": "Steady demand — organizations always need clearer decisions.",
    },
    {
        "slug": "digital-marketer",
        "title": "Digital Marketer",
        "category": "business",
        "emoji": "📣",
        "summary": "Tells the world about products through content, ads, data and psychology.",
        "description": "Digital Marketers grow brands online. You craft campaigns, write copy, run ads, analyze what converts and make sure the right people find a product and love it.",
        "what_they_do": "Plan campaigns across social, search and email. Create content and copy. Run and optimize ad spend. Analyze data to improve performance. Build brand stories.",
        "skills": ["creativity", "communication", "data analysis", "psychology", "copywriting", "curiosity"],
        "subjects": ["business", "psychology", "economics", "media"],
        "degrees": ["Business", "Marketing", "Media", "Psychology"],
        "industries": ["E-commerce", "Technology", "Consumer brands", "Agencies", "Startups"],
        "future_paths": ["Growth Marketer", "Brand Manager", "CMO", "Growth Consultant"],
        "salary_range": "$80k - $150k (India: ₹10-35L)",
        "outlook": "Strong — every brand increasingly lives online.",
    },
    {
        "slug": "doctor",
        "title": "Doctor (Physician)",
        "category": "medicine",
        "emoji": "🩺",
        "summary": "Diagnoses, treats and cares for patients — one of the most trusted roles in society.",
        "description": "Doctors protect health. You study the human body, diagnose illness, treat disease and help people live better — a long, demanding but deeply meaningful path.",
        "what_they_do": "Examine and diagnose patients. Prescribe treatment. Perform procedures. Monitor recovery. Communicate with patients and families. Keep learning for life.",
        "skills": ["problem solving", "empathy", "communication", "resilience", "attention to detail", "science literacy"],
        "subjects": ["biology", "chemistry", "physics", "mathematics"],
        "degrees": ["MBBS", "MD", "Specialty Residency"],
        "industries": ["Hospitals", "Clinics", "Research", "Public Health"],
        "future_paths": ["Specialist (Cardiology, Surgery...)", "Surgeon", "Hospital Leader", "Medical Researcher"],
        "salary_range": "$200k - $400k+ (India: ₹15-60L depending on specialty)",
        "outlook": "Always needed — one of the most durable careers.",
    },
    {
        "slug": "psychologist",
        "title": "Psychologist",
        "category": "psychology",
        "emoji": "🧠",
        "summary": "Understands how people think, feel and behave — and helps them thrive.",
        "description": "Psychologists study the mind and behavior. Some help individuals thrive through therapy; others work with organizations or run research that changes how we live.",
        "what_they_do": "Assess mental health and behavior. Provide therapy and support. Design interventions. Conduct research. Work with schools, companies and communities.",
        "skills": ["empathy", "active listening", "communication", "critical thinking", "patience", "research"],
        "subjects": ["psychology", "biology", "mathematics", "statistics"],
        "degrees": ["Psychology", "Clinical Psychology", "Counselling"],
        "industries": ["Healthcare", "Education", "HR / Organizations", "Research", "Tech (UX)"],
        "future_paths": ["Clinical Psychologist", "Counsellor", "Organizational Psychologist", "Professor / Researcher"],
        "salary_range": "$80k - $150k (India: ₹8-25L)",
        "outlook": "Growing strongly — mental health is now a global priority.",
    },
    {
        "slug": "financial-analyst",
        "title": "Financial Analyst",
        "category": "finance",
        "emoji": "💹",
        "summary": "Analyzes companies and markets to guide smart investment decisions.",
        "description": "Financial Analysts figure out what investments are worth. You study companies, build financial models, predict performance and recommend where money should go.",
        "what_they_do": "Build financial models. Analyze markets and companies. Prepare reports and valuations. Forecast budgets. Advise on investments and strategy.",
        "skills": ["analytical thinking", "mathematics", "attention to detail", "financial modelling", "communication"],
        "subjects": ["mathematics", "economics", "accounting", "business"],
        "degrees": ["Finance", "Economics", "Accounting", "Business"],
        "industries": ["Banking", "Investment", "Consulting", "Corporate Finance", "Asset Management"],
        "future_paths": ["Senior Analyst", "Portfolio Manager", "Investment Banker", "CFO"],
        "salary_range": "$100k - $200k (India: ₹15-40L)",
        "outlook": "Strong — every organization makes financial decisions.",
    },
    {
        "slug": "civil-engineer",
        "title": "Civil Engineer",
        "category": "engineering",
        "emoji": "🏗️",
        "summary": "Designs and builds bridges, roads, buildings and the infrastructure civilization runs on.",
        "description": "Civil Engineers build physical infrastructure. You design structures that are safe, sustainable and built to last — from skyscrapers to clean water systems.",
        "what_they_do": "Design structures and infrastructure. Run safety and feasibility analysis. Manage construction projects. Coordinate with architects and contractors. Ensure quality and compliance.",
        "skills": ["mathematics", "physics", "problem solving", "project management", "attention to detail"],
        "subjects": ["mathematics", "physics", "chemistry"],
        "degrees": ["Civil Engineering", "Structural Engineering"],
        "industries": ["Construction", "Infrastructure", "Real Estate", "Government"],
        "future_paths": ["Senior Engineer", "Project Manager", "Structural Consultant", "Entrepreneur"],
        "salary_range": "$90k - $160k (India: ₹10-30L)",
        "outlook": "Steady — infrastructure is a permanent need.",
    },
    {
        "slug": "robotics-engineer",
        "title": "Robotics Engineer",
        "category": "engineering",
        "emoji": "🦾",
        "summary": "Builds machines that move, sense and act — from factory arms to self-driving cars.",
        "description": "Robotics Engineers combine mechanical design, electronics and AI to build machines that can act in the physical world. It's where software meets hardware.",
        "what_they_do": "Design robot mechanisms and controls. Write software for sensing and autonomy. Build and test prototypes. Integrate electronics and motors. Optimize performance and safety.",
        "skills": ["programming", "mathematics", "mechanics", "electronics", "problem solving", "physics"],
        "subjects": ["mathematics", "physics", "computer science", "electronics"],
        "degrees": ["Robotics", "Mechatronics", "Mechanical Engineering", "Computer Science"],
        "industries": ["Manufacturing", "Automotive", "Healthcare robotics", "Aerospace", "Logistics"],
        "future_paths": ["Senior Robotics Engineer", "Autonomy Lead", "Hardware Lead", "Founder"],
        "salary_range": "$110k - $180k (India: ₹15-45L)",
        "outlook": "Strong and accelerating with automation.",
    },
    {
        "slug": "research-scientist",
        "title": "Research Scientist",
        "category": "science",
        "emoji": "🔬",
        "summary": "Explores the unknown and creates new knowledge that changes the world.",
        "description": "Research Scientists push the edge of what's known — in labs, in tech companies and in the field. You design experiments, analyze data and publish discoveries.",
        "what_they_do": "Design and run experiments. Analyze data and results. Read and write scientific papers. Collaborate across disciplines. Present findings to peers and the public.",
        "skills": ["curiosity", "critical thinking", "mathematics", "experimentation", "writing", "resilience"],
        "subjects": ["biology", "chemistry", "physics", "mathematics"],
        "degrees": ["BSc / MSc / PhD in a science"],
        "industries": ["Universities", "Tech (AI) research", "Pharma", "Government labs", "Biotech"],
        "future_paths": ["Principal Investigator", "Head of Research", "Chief Scientist", "Professor"],
        "salary_range": "$100k - $200k (India: ₹12-40L)",
        "outlook": "Steady in academia; booming in AI and biotech.",
    },
    {
        "slug": "lawyer",
        "title": "Lawyer",
        "category": "law",
        "emoji": "⚖️",
        "summary": "Advocates for people and ideas — and shapes how society makes rules.",
        "description": "Lawyers interpret and use the law to protect, advise and represent people and organizations. You research, argue, negotiate and write with precision.",
        "what_they_do": "Research legal issues. Draft contracts and documents. Advise clients. Negotiate settlements. Represent clients in court and before regulators.",
        "skills": ["critical thinking", "communication", "research", "persuasion", "attention to detail", "ethics"],
        "subjects": ["history", "political science", "english", "economics"],
        "degrees": ["Law (LLB / JD)", "Law + specializations"],
        "industries": ["Law firms", "Courts", "Corporate", "Government", "NGOs"],
        "future_paths": ["Corporate Lawyer", "Advocate", "Judge (later)", "Legal Counsel", "Policymaker"],
        "salary_range": "$120k - $250k (India: ₹10-50L)",
        "outlook": "Steady — law grows with the complexity of the world.",
    },
    {
        "slug": "journalist",
        "title": "Journalist",
        "category": "media",
        "emoji": "📰",
        "summary": "Finds and tells the stories people need to know — simply and truthfully.",
        "description": "Journalists investigate, verify and report the news. You find stories, interview people, verify facts and share them through writing, video, audio or social media.",
        "what_they_do": "Pitch and research stories. Conduct interviews. Verify facts and sources. Write, edit or produce content. Publish across platforms and adapt to audiences.",
        "skills": ["writing", "curiosity", "communication", "research", "critical thinking", "resilience"],
        "subjects": ["english", "history", "political science", "media"],
        "degrees": ["Journalism", "Media", "English", "Political Science"],
        "industries": ["News", "Magazines", "Digital media", "Broadcast", "Podcasting"],
        "future_paths": ["Senior Reporter", "Editor", "News Anchor", "Foreign Correspondent", "Media Founder"],
        "salary_range": "$60k - $140k (India: ₹8-30L)",
        "outlook": "Evolving — great storytellers are still in demand.",
    },
    {
        "slug": "teacher",
        "title": "School Teacher / Educator",
        "category": "education",
        "emoji": "🍎",
        "summary": "Shapes the future by helping young people learn, think and grow.",
        "description": "Great teachers change lives. You plan lessons, explain ideas, inspire curiosity and guide students — in a classroom, online or through EdTech tools.",
        "what_they_do": "Plan and deliver lessons. Assess and support students. Adapt to different learners. Mentor and guide. Design learning experiences (often technology-enhanced).",
        "skills": ["communication", "empathy", "patience", "creativity", "leadership", "public speaking"],
        "subjects": ["Your subject + education"],
        "degrees": ["Education", "Subject degree + teaching certification"],
        "industries": ["Schools", "EdTech", "Tutoring", "Content", "Training"],
        "future_paths": ["Lead Teacher", "Curriculum Designer", "EdTech Founder", "Principal"],
        "salary_range": "$50k - $110k (India: ₹6-20L)",
        "outlook": "Stable — and expanding rapidly through EdTech.",
    },
]

# Full catalog = hand-written flagship careers merged with the generated master
# list. Hand-written entries win on slug collisions; any missing ranking fields
# are back-filled from an appropriate profile.
_FLAGSHIP_PROFILE = {
    "product-manager": "TECH",
    "ai-engineer": "AI_DATA",
    "software-engineer": "TECH",
    "cybersecurity-analyst": "CYBER",
    "data-scientist": "AI_DATA",
    "game-developer": "MEDIA",
    "ux-designer": "CREATIVE",
    "product-designer": "CREATIVE",
    "architect": "CREATIVE",
    "entrepreneur": "ENTREPRENEUR",
    "business-analyst": "BUSINESS",
    "digital-marketer": "BUSINESS",
    "doctor": "HEALTH",
    "psychologist": "HEALTH",
    "financial-analyst": "FINANCE",
    "civil-engineer": "ENGINEERING",
    "robotics-engineer": "ENGINEERING",
    "research-scientist": "SCIENCE",
    "lawyer": "LAW",
    "journalist": "MEDIA",
    "teacher": "EDU",
}


def _merge_catalog() -> list[dict]:
    merged = {c["slug"]: c for c in _detailed_careers()}
    for slug, profile in _FLAGSHIP_PROFILE.items():
        if slug in merged:
            merged[slug]["ranking_profile"] = profile
            merged[slug]["country_rankings"] = RANKING_PROFILES[profile]
    # Every hand-written entry that still lacks ranking data gets a safe default.
    for c in merged.values():
        c["category"] = normalize_category(c.get("category"))
        c.setdefault("ranking_profile", "DEFAULT")
        c.setdefault("country_rankings", RANKING_PROFILES["DEFAULT"])
        if "ranking_profile" in c:
            c.setdefault("country_rankings", RANKING_PROFILES.get(c["ranking_profile"], RANKING_PROFILES["DEFAULT"]))
    return merged


CAREERS: list[dict] = list(_merge_catalog().values()) + [
    build_career(title, category, profile)
    for (title, category, profile) in CAREERS_TUPLES
    if slugify(title) not in _merge_catalog()
]

UNIVERSITIES: list[dict] = [
    {
        "slug": "stanford-computer-science",
        "name": "Stanford University",
        "country": "USA",
        "city": "Palo Alto",
        "course": "Computer Science",
        "subject": "computer science",
        "ranking": 3,
        "fees_per_year": 62000,
        "university_type": "private",
        "scholarships": True,
        "entry_requirements": "Top grades (A/A*), strong SAT/ACT, compelling essays, demonstrated interest in CS/AI, extracurricular depth.",
        "about": "The heart of Silicon Valley's startup culture. World-leading AI (Google DeepMind roots, ChatGPT alumni), incredible research and an unmatched founder ecosystem.",
        "website": "https://www.stanford.edu",
        "tags": ["ai", "ml", "startups", "entrepreneurship", "research"],
        "strengths": ["#1 for AI & CS research", "Unmatched startup culture", "Massive alumni network in tech"],
    },
    {
        "slug": "mit-eecs",
        "name": "MIT",
        "country": "USA",
        "city": "Cambridge",
        "course": "Electrical Engineering & Computer Science",
        "subject": "computer science",
        "ranking": 2,
        "fees_per_year": 60000,
        "university_type": "private",
        "scholarships": True,
        "entry_requirements": "Exceptional academics and SAT/ACT, standout projects, strong math olympiad/competition record.",
        "about": "The world's most rigorous engineering school. Famous for hands-on learning, competitions, and an unmatched brand in tech recruiting.",
        "website": "https://web.mit.edu",
        "tags": ["engineering", "robotics", "math", "research"],
        "strengths": ["#1 globally in several engineering fields", "Hands-on 'mens et manus' culture", "Elite technology brand"],
    },
    {
        "slug": "uc-berkeley-eecs",
        "name": "UC Berkeley",
        "country": "USA",
        "city": "Berkeley",
        "course": "Electrical Engineering & Computer Science",
        "subject": "computer science",
        "ranking": 6,
        "fees_per_year": 44000,
        "university_type": "public",
        "scholarships": True,
        "entry_requirements": "Strong GPA, SAT/ACT, essays; emphasis on demonstrated interest in CS and contributions to community.",
        "about": "One of the strongest public universities in the world for CS — right next to Silicon Valley, with deep AI/ML roots.",
        "website": "https://www.berkeley.edu",
        "tags": ["ai", "cs", "public", "silicon valley"],
        "strengths": ["Top-5 CS program", "Adjacent to the Bay Area tech industry", "Strong AI & systems research"],
    },
    {
        "slug": "harvard-computer-science",
        "name": "Harvard University",
        "country": "USA",
        "city": "Cambridge (MA)",
        "course": "Computer Science",
        "subject": "computer science",
        "ranking": 5,
        "fees_per_year": 59000,
        "university_type": "private",
        "scholarships": True,
        "entry_requirements": "Outstanding academics, SAT/ACT, essays and recommendations; leadership and impact important.",
        "about": "A brand like no other. CS at Harvard combines elite teaching with a powerful global network — and generous financial aid.",
        "website": "https://www.harvard.edu",
        "tags": ["cs", "leadership", "brand", "finance"],
        "strengths": ["World-famous brand & network", "Strong CS + interdisciplinary options", "Excellent need-based aid"],
    },
    {
        "slug": "oxford-computer-science",
        "name": "University of Oxford",
        "country": "UK",
        "city": "Oxford",
        "course": "Computer Science",
        "subject": "computer science",
        "ranking": 8,
        "fees_per_year": 48000,
        "university_type": "public",
        "scholarships": True,
        "entry_requirements": "A* in Maths + A in further subjects, exceptional aptitude in problem solving (interview-based admissions).",
        "about": "800 years of academic excellence. Small tutorial teaching, rigorous mathematics and deep theory in CS.",
        "website": "https://www.ox.ac.uk",
        "tags": ["theory", "mathematics", "tutorials", "uk"],
        "strengths": ["Tutorial-style teaching", "World-class theory & mathematics", "Historic global reputation"],
    },
    {
        "slug": "imperial-college-computing",
        "name": "Imperial College London",
        "country": "UK",
        "city": "London",
        "course": "Computing",
        "subject": "computer science",
        "ranking": 12,
        "fees_per_year": 45000,
        "university_type": "public",
        "scholarships": True,
        "entry_requirements": "Strong A-levels (A*A*A) with Maths, high admissions test performance, coding aptitude.",
        "about": "Science-focused powerhouse in London with excellent placement rates and strong industry links in Europe's biggest tech hub.",
        "website": "https://www.imperial.ac.uk",
        "tags": ["engineering", "london", "placement", "uk"],
        "strengths": ["Elite engineering reputation", "Exceptional employment outcomes", "Central London tech scene"],
    },
    {
        "slug": "eth-zurich-computer-science",
        "name": "ETH Zurich",
        "country": "Switzerland",
        "city": "Zurich",
        "course": "Computer Science",
        "subject": "computer science",
        "ranking": 10,
        "fees_per_year": 1600,
        "university_type": "public",
        "scholarships": False,
        "entry_requirements": "Strong mathematical background, competitive entry (often via aptitude exam for internationals), excellent grades.",
        "about": "One of Europe's best for CS and robotics (home of famous AI research). Incredibly low fees, rigorous academics.",
        "website": "https://ethz.ch",
        "tags": ["robotics", "ai", "low-fee", "europe"],
        "strengths": ["Top European research university", "Very low tuition", "Strong robotics/AI cluster"],
    },
    {
        "slug": "nus-computer-science",
        "name": "National University of Singapore",
        "country": "Singapore",
        "city": "Singapore",
        "course": "Computer Science",
        "subject": "computer science",
        "ranking": 11,
        "fees_per_year": 30000,
        "university_type": "public",
        "scholarships": True,
        "entry_requirements": "Excellent academic record, strong math, competitive admissions; scholarships available.",
        "about": "Asia's leading university — a gateway to the region's booming tech economy with exceptional global rankings.",
        "website": "https://www.nus.edu.sg",
        "tags": ["asia", "singapore", "global", "research"],
        "strengths": ["Top university in Asia", "Global tech gateway", "Strong funded research"],
    },
    {
        "slug": "waterloo-software-engineering",
        "name": "University of Waterloo",
        "country": "Canada",
        "city": "Waterloo",
        "course": "Software Engineering",
        "subject": "computer science",
        "ranking": 30,
        "fees_per_year": 28000,
        "university_type": "public",
        "scholarships": True,
        "entry_requirements": "Strong high-school math & science, competitive admissions; co-op program places students at top tech firms.",
        "about": "Home of the legendary co-op program that sends students to Apple, Google and beyond — great for builders.",
        "website": "https://uwaterloo.ca",
        "tags": ["co-op", "careers", "canada", "engineering"],
        "strengths": ["World-famous co-op program", "Huge tech employment outcomes", "Strong software engineering"],
    },
    {
        "slug": "iit-bombay-cs",
        "name": "IIT Bombay",
        "country": "India",
        "city": "Mumbai",
        "course": "Computer Science & Engineering",
        "subject": "computer science",
        "ranking": 20,
        "fees_per_year": 2500,
        "university_type": "public",
        "scholarships": True,
        "entry_requirements": "Top rank in JEE Advanced — among the most competitive entrance exams in the world.",
        "about": "India's most prestigious technology institute. Elite peer group, strong startup culture and exceptional campus placements.",
        "website": "https://www.iitb.ac.in",
        "tags": ["india", "jee", "placements", "startups"],
        "strengths": ["Elite national brand", "Top placements in India", "Strong startup ecosystem"],
    },
    {
        "slug": "iit-delhi-cs",
        "name": "IIT Delhi",
        "country": "India",
        "city": "New Delhi",
        "course": "Computer Science & Engineering",
        "subject": "computer science",
        "ranking": 22,
        "fees_per_year": 2500,
        "university_type": "public",
        "scholarships": True,
        "entry_requirements": "Top rank in JEE Advanced.",
        "about": "Another flagship Indian institute — known for research, strong alumni in global tech, and superb placements.",
        "website": "https://home.iitd.ac.in",
        "tags": ["india", "jee", "placements", "research"],
        "strengths": ["Research strength", "Global CS alumni network", "Top Indian placements"],
    },
    {
        "slug": "bits-pilani-cs",
        "name": "BITS Pilani",
        "country": "India",
        "city": "Pilani",
        "course": "Computer Science",
        "subject": "computer science",
        "ranking": 40,
        "fees_per_year": 6000,
        "university_type": "private",
        "scholarships": True,
        "entry_requirements": "Admission via BITSAT, moderate-strong scores, first-come placements for CS.",
        "about": "Popular private institute with a huge alumni base in software — flexible and strong in computer science.",
        "website": "https://www.bits-pilani.ac.in",
        "tags": ["india", "private", "bitsat", "software"],
        "strengths": ["Large tech alumni base", "Flexible academic programs", "Admission without JEE"],
    },
    {
        "slug": "cambridge-engineering",
        "name": "University of Cambridge",
        "country": "UK",
        "city": "Cambridge",
        "course": "Engineering",
        "subject": "engineering",
        "ranking": 4,
        "fees_per_year": 48500,
        "university_type": "public",
        "scholarships": True,
        "entry_requirements": "Outstanding A-levels with Maths & Physics, strong admissions assessment, interview.",
        "about": "The world's oldest university with an engineering program renowned for depth, supervision teaching and prestige.",
        "website": "https://www.cam.ac.uk",
        "tags": ["engineering", "uk", "prestige", "research"],
        "strengths": ["Global prestige", "Supervision teaching", "Strong engineering research"],
    },
    {
        "slug": "carnegie-mellon-computer-science",
        "name": "Carnegie Mellon University",
        "country": "USA",
        "city": "Pittsburgh",
        "course": "Computer Science",
        "subject": "computer science",
        "ranking": 1,
        "fees_per_year": 62000,
        "university_type": "private",
        "scholarships": True,
        "entry_requirements": "Exceptional academics and competition record; highly selective CS school known for rigor.",
        "about": "Ranked #1 for Computer Science in the US. Famous for turning out elite engineers, researchers and founders.",
        "website": "https://www.cmu.edu",
        "tags": ["cs", "robotics", "ai", "elite"],
        "strengths": ["#1 ranked CS program", "Legendary rigor", "Top-tier AI & robotics labs"],
    },
]


def seed(db: Session) -> dict:
    created = {"careers": 0, "universities": 0}

    if db.scalar(select(Career.id).limit(1)) is None:
        db.add_all([Career(**c) for c in CAREERS])
        created["careers"] = len(CAREERS)

    if db.scalar(select(University.id).limit(1)) is None:
        db.add_all([University(**u) for u in UNIVERSITIES])
        created["universities"] = len(UNIVERSITIES)

    db.commit()
    return created